import { ThemeProvider } from '@/components/ThemeProvider';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Lexend, Syne } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import './globals.css';

const lexend = Lexend({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-default'
});

const displayFont = Syne({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-display'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body
        className={cn(lexend.variable, displayFont.variable, 'scroll-smooth')}
      >
        <NextTopLoader
          color='hsl(var(--primary))'
          shadow='0 0 10px hsl(var(--primary)),0 0 5px hsl(var(--primary))'
        />
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
